#!/bin/bash


#set -e # play it safe      # Causes problems apparently...

echo "ROOT IS REQUIRED TO ADD OLDSU TO /usr/bin and /usr/share"
sudo echo "Thanks!"

if [[ $? != 0 ]] ; then
  exit
fi

TMP_DIR="/tmp/oldsu-wine"
mkdir -p "$TMP_DIR"
cd "$TMP_DIR" # Create tmp files here.

# Styling
BORDER="========================================================================"

print_sect () {
  echo $BORDER
  echo "$1"
  echo $BORDER
}

# maybe change to a check that prompts to grab latest winetricks if not installed if I find out how to do so
print_sect "ATTENTION: THIS SCRIPT ASSUMES WINE AND WINETRICKS ARE ALREADY INSTALLED"



# Wine environ
if [[ ! -n "$WINEPREFIX" ]] ; then
  export WINEPREFIX="$HOME/Games/oldsu-wine"
fi
if [[ ! -n "$WINE" ]] ; then
  export WINE="wine"
fi
if [[ ! -n "$WINESERVER" ]] ; then
  export WINESERVER="wineserver"
fi
if [[ ! -n "$WINETRICKS" ]] ; then
  export WINETRICKS="winetricks"
fi
if [[ ! -n "$WINECFG" ]] ; then
  export WINECFG="winecfg"
fi
export WINEARCH=win32



# COMMANDS
WINETRICKS_CREATE_PREFIX="$WINETRICKS -q --force dotnet48 cjkfonts gdiplus ffdshow quartz"
WINETRICKS_ALSA="$WINETRICKS sound=alsa"

# Create wineprefix
print_sect "CREATING WINEPREFIX"
$WINETRICKS_CREATE_PREFIX


# Manual winecfg step
print_sect "MANUAL STEP"
echo "> \"navigate to graphics and ensure that "allow the window manager to decorate the windows" and "allow the window manager to control the windows" are enabled. this can allow native fullscreen to work which can help performance on bloated desktop environments like gnome\""
echo "See https://osu.ppy.sh/community/forums/topics/367783"

"$WINECFG"

print_sect "ALSA"

if [[ "$ALSATWEAK" == "true" ]]; then
  $WINETRICKS_ALSA
else
  echo "SKIPPING ALSA TWEAK"
fi

# change directory to newly created prefix
cd "$HOME/Games/oldsu-wine"

# dsound tweak
print_sect "dsound tweak"
cat > dsound.reg << "EOF"
Windows Registry Editor Version 5.00


[HKEY_CURRENT_USER\Software\Wine\DirectSound]

"HelBuflen"="512"

"SndQueueMax"="3"

EOF

"$WINE" regedit dsound.reg

print_sect "oldsu! installer step. PLEASE CLOSE OLDSU WHEN LAUNCHED."
# oldsu! Installer

if [[ -e "stable.zip" ]]; then
  echo "oldsu! archive already downloaded!"
  echo "Extracting archive now."
  mkdir "$HOME/Games/oldsu-wine/drive_c/users/$USER/Local Settings/Application Data/oldsu!"
  unzip 'stable.zip' -d "$HOME/Games/oldsu-wine/drive_c/users/$USER/Local Settings/Application Data/oldsu!"
else
  wget -O 'stable.zip' 'https://oldsu.ayyeve.xyz/releases/stable.zip'
  mkdir "$HOME/Games/oldsu-wine/drive_c/users/$USER/Local Settings/Application Data/oldsu!"
  unzip 'stable.zip' -d "$HOME/Games/oldsu-wine/drive_c/users/$USER/Local Settings/Application Data/oldsu!"
fi

"$WINE" "osu!flandremod.exe"


print_sect "POST INSTALL STEPS"
# Post install
OLDSU_SC_PATH="$HOME/Games/oldsu"

if [[ ! -e $OLDSU_SC_PATH ]] ; then
  ln -sv "$WINEPREFIX/drive_c/users/$USER/Local Settings/Application Data/oldsu!" "$OLDSU_SC_PATH"
  echo "Created oldsu! folder shortcut in current user's home."
fi

# Launch script

print_sect "REQUESTING ROOT ACCESS TO ADD OLDSU TO /usr/bin"

cat > oldsu << "EOF"
#!/bin/sh


export vblank_mode=0

export WINEARCH=win32

EOF

echo "export WINEPREFIX=\"$WINEPREFIX\""  >> oldsu
echo "\"$WINE\" \"$WINEPREFIX/drive_c/users/\$USER/Local Settings/Application Data/oldsu!/osu!flandremod.exe\" \"\$@\"" >> oldsu


sudo mv oldsu /usr/bin/oldsu
sudo chmod +x /usr/bin/oldsu



# Kill script
cat > oldsukill << "EOF"
#!/bin/sh


export vblank_mode=0

export WINEARCH=win32

EOF

echo "export WINEPREFIX=\"$WINEPREFIX\"" >> oldsukill
echo "\"$WINESERVER\" -k" >> oldsukill


sudo mv oldsukill /usr/bin/oldsukill
sudo chmod +x /usr/bin/oldsukill



print_sect "REQUESTING ROOT ACCESS TO ADD OLDSU DESKTOP FILE TO /usr/share"

# Desktop file

OLDSU_LOGO_URL="https://cdn.discordapp.com/attachments/762549406091575309/783088957776461824/oldsu.png"

sudo wget "$OLDSU_LOGO_URL" -O "/usr/share/icons/oldsulogo.png"

cat > "oldsu!.desktop" << "EOF"
[Desktop Entry]

Encoding=UTF-8

Name=oldsu!

Comment=Travel back in time! Launch the 2008 o(ld)su! client.

Type=Application

Exec=oldsu %F

Icon=oldsulogo

StartupWMClass=osu!flandremod.exe

Categories=

EOF

sudo mv "oldsu!.desktop" "/usr/share/applications"
sudo chmod +x "/usr/share/applications/oldsu!.desktop"





# Cleanup
cd /tmp
rm -r "$TMP_DIR"


# Finished!
print_sect "Finished! Please report any issues with this script at https://github.com/marshallracer/osu-wine-install-script"

