#!/bin/bash

echo "ROOT IS REQUIRED TO ADD OSU TO /usr/bin and /usr/share"
sudo echo "Thanks!"

if [[ $? != 0 ]] ; then
  exit
fi

TMP_DIR="/tmp/oldsu-wine"
mkdir -p "$TMP_DIR"
cd "$TMP_DIR" # Create tmp files here.

# Styling
BORDER="========================================================================"

print_sect () {
  echo $BORDER
  echo "$1"
  echo $BORDER
}

# jvyden's dep-checks method has been replaced
echo -e "Checking if dependencies are installed...\n"

for i in $(cat dependencies.list); do
	which $i > /dev/null
	if [[ $? == "1" ]]; then
		echo "Dependency \"$i\" not found"
		missing_deps=true
	fi
done

if [[ $missing_deps ]]; then
	echo -e "\nInstall missing dependencies and try again"
	exit 1
fi

# set Wine environment variables for installation - change to your liking or needs before installation
if [[ ! -n "$WINEPREFIX" ]] ; then
  export WINEPREFIX="$HOME/Games/oldsu-wine"
fi
if [[ ! -n "$WINE" ]]; then
  export WINE="wine"
fi
if [[ ! -n "$WINESERVER" ]]; then
  export WINESERVER="wineserver"
fi
if [[ ! -n "$WINETRICKS" ]]; then
  export WINETRICKS="winetricks"
fi
if [[ ! -n "$DISCORDRPC" ]]; then
  export DISCORDRPC="true"
fi
export WINEARCH=win32


# Create wineprefix
print_sect "CREATING WINEPREFIX"
echo "If wine asks you to install wine mono or wine gecko, say no or cancel. This will cause problems later."
$WINETRICKS --force dotnet45 # force flag for recent wine 5.x versions; no -q so the user knows whats happening
$WINETRICKS -q cjkfonts gdiplus ffdshow quartz # fixes fonts, graphics and videos


# change directory to newly created prefix
cd "$WINEPREFIX"

# dsound tweak
print_sect "dsound tweak"
cat > dsound.reg << "EOF"
Windows Registry Editor Version 5.00


[HKEY_CURRENT_USER\Software\Wine\DirectSound]

"HelBuflen"="512"

"SndQueueMax"="3"

EOF

"$WINE" regedit dsound.reg

# oldsu! Installer
print_sect "Installing oldsu!..."

if [[ -e "stable.zip" ]]; then
  echo "oldsu! archive already downloaded, if this is out of date either oldsu will update itself or you will need to remove stable.zip."
else
  echo "Downloading archive..."
  wget -O 'stable.zip' 'https://oldsu.ayyeve.xyz/releases/stable.zip'
fi
echo "Extracting archive..."
mkdir "$WINEPREFIX/drive_c/oldsu"
unzip 'stable.zip' -d "$WINEPREFIX/drive_c/oldsu"


print_sect "POST INSTALL STEPS"
# Post install
OLDSU_SC_PATH="$HOME/Games/oldsu"

if [[ ! -e $OLDSU_SC_PATH ]] ; then
  ln -sv "$WINEPREFIX/drive_c/oldsu" "$OLDSU_SC_PATH"
  echo "Created oldsu! folder shortcut in current user's home."
fi

# Launch script
cat > oldsu << "EOF"
#!/bin/sh
export vblank_mode=0
export WINEARCH=win32
EOF

echo "export WINEPREFIX=\"$WINEPREFIX\""  >> oldsu
echo "cd \"$WINEPREFIX/drive_c/oldsu\"" >> oldsu

print_sect "Discord RPC"
if [[ "$DISCORDRPC" == "true" ]]; then
  echo "Downloading Discord RPC bridge..."
  curl -O -J -L 'https://github.com/0e4ef622/wine-discord-ipc-bridge/releases/download/v0.0.1/winediscordipcbridge.exe'
  mv "winediscordipcbridge.exe" "$WINEPREFIX/drive_c/oldsu/"
  echo "\"$WINE\" \"$WINEPREFIX/drive_c/oldsu/winediscordipcbridge.exe\" &" >> oldsu
else
  echo "Skipping Discord RPC install."
fi

echo "\"$WINE\" \"$WINEPREFIX/drive_c/oldsu/osu!flandremod.exe\" \"\$@\"" >> oldsu

print_sect "REQUESTING ROOT ACCESS TO ADD OLDSU TO /usr/bin"
sudo mv oldsu /usr/bin/oldsu
sudo chmod +x /usr/bin/oldsu

# Kill script
cat > oldsukill << "EOF"
#!/bin/sh
export WINEARCH=win32
EOF

echo "export WINEPREFIX=\"$WINEPREFIX\"" >> oldsukill
echo "\"$WINESERVER\" -k" >> oldsukill

sudo mv oldsukill /usr/bin/oldsukill
sudo chmod +x /usr/bin/oldsukill

# Desktop file
OLDSU_LOGO_URL="https://cdn.discordapp.com/attachments/762549406091575309/783088957776461824/oldsu.png"
wget "$OLDSU_LOGO_URL" -O "$HOME/.local/share/icons/oldsulogo.png"

cat > "oldsu!.desktop" << "EOF"
[Desktop Entry]

Encoding=UTF-8

Name=oldsu!

Comment=Travel back in time! Launch the 2008 o(ld)su! client.

Type=Application

Exec=oldsu %F

Icon=oldsulogo

StartupWMClass=osu!flandremod.exe

Categories=Games

EOF

mv "oldsu!.desktop" "$HOME/.local/share/applications"
chmod +x "$HOME/.local/share/applications/oldsu!.desktop"

# Cleanup
cd /tmp
rm -r "$TMP_DIR"

# Finished!
print_sect "Finished! Please report any issues with this script at https://github.com/marshallracer/osu-wine-install-script"
