#!/bin/bash

TMP_DIR="/tmp/oldsu-wine"
mkdir -p "$TMP_DIR"
cd "$TMP_DIR" # Create tmp files here.

# Styling
BORDER="========================================================================"

print_sect () {
  echo $BORDER
  echo "$1"
  echo $BORDER
}


# thanks to j4yden for dep-checks
echo "Checking to see if wine and winetricks are installed..."

if [ ! command -v wine &> /dev/null ]; then
  echo "Wine is not installed! Exiting."
  exit 1
fi

if [ ! command -v winetricks &> /dev/null ]; then
  echo "Winetricks is not installed! Exiting."
  exit 1
fi

if [ ! command -v wget &> /dev/null ]; then
  echo "wget is not installed! Exiting."
  exit 1
fi

if [ ! command -v curl &> /dev/null ]; then
  echo "curl is not installed! Exiting."
  exit 1
fi


# set Wine environment variables for installation - change to your liking or needs before installation
if [[ ! -n "$WINEPREFIX" ]] ; then
  export WINEPREFIX="$HOME/Games/oldsu-wine"
fi
if [[ ! -n "$WINE" ]]; then
  export WINE="wine"
fi
if [[ ! -n "$WINESERVER" ]]; then
  export WINESERVER="wineserver"
fi
if [[ ! -n "$WINETRICKS" ]]; then
  export WINETRICKS="winetricks"
fi
if [[ ! -n "$WINECFG" ]]; then
  export WINECFG="winecfg"
fi
if [[ ! -n "$DISCORDRPC" ]]; then
  export DISCORDRPC="true"
fi
export WINEARCH=win32


# Create wineprefix
print_sect "CREATING WINEPREFIX"
echo "If wine asks you to install wine mono or wine gecko, say no or cancel. This will cause problems later."
$WINETRICKS --force dotnet45 # force flag for recent wine 5.x versions; no -q so the user knows whats happening
$WINETRICKS -q cjkfonts gdiplus ffdshow quartz # fixes fonts, graphics and videos


# Manual winecfg step
print_sect "MANUAL STEP"
echo "> \"navigate to graphics and ensure that "allow the window manager to decorate the windows" and "allow the window manager to control the windows" are enabled. this can allow native fullscreen to work which can help performance on bloated desktop environments like gnome\""
echo "See https://osu.ppy.sh/community/forums/topics/367783"

"$WINECFG"

read -n 1 -s -r -p "Press any key when you are done with this step."

print_sect "ALSA"

if [[ "$ALSATWEAK" == "true" ]]; then
  $WINETRICKS sound=alsa
else
  echo "Skipping ALSA tweak."
fi


# change directory to newly created prefix
cd "$WINEPREFIX"

# dsound tweak
print_sect "dsound tweak"
cat > dsound.reg << "EOF"
Windows Registry Editor Version 5.00


[HKEY_CURRENT_USER\Software\Wine\DirectSound]

"HelBuflen"="512"

"SndQueueMax"="3"

EOF

"$WINE" regedit dsound.reg

# oldsu! Installer
print_sect "Installing oldsu!..."

if [[ -e "stable.zip" ]]; then
  echo "oldsu! archive already downloaded, if this is out of date either oldsu will update itself or you will need to remove stable.zip."
else
  echo "Downloading archive..."
  wget -O 'stable.zip' 'https://oldsu.ayyeve.xyz/releases/stable.zip'
fi
echo "Extracting archive..."
mkdir "$WINEPREFIX/drive_c/oldsu"
unzip 'stable.zip' -d "$WINEPREFIX/drive_c/oldsu"


print_sect "POST INSTALL STEPS"
# Post install
OLDSU_SC_PATH="$HOME/Games/oldsu"

if [[ ! -e $OLDSU_SC_PATH ]] ; then
  ln -sv "$WINEPREFIX/drive_c/oldsu" "$OLDSU_SC_PATH"
  echo "Created oldsu! folder shortcut in current user's home."
fi

# Launch script
cat > oldsu << "EOF"
#!/bin/sh
export vblank_mode=0
export WINEARCH=win32
EOF

echo "export WINEPREFIX=\"$WINEPREFIX\""  >> oldsu

print_sect "Discord RPC"
if [[ "$DISCORDRPC" == "true" ]]; then
  echo "Downloading Discord RPC bridge..."
  curl -O -J -L 'https://github.com/0e4ef622/wine-discord-ipc-bridge/releases/download/v0.0.1/winediscordipcbridge.exe'
  mv "winediscordipcbridge.exe" "$WINEPREFIX/drive_c/oldsu/"
  echo "\"$WINE\" \"$WINEPREFIX/drive_c/oldsu/winediscordipcbridge.exe\" &" >> oldsu
else
  echo "Skipping Discord RPC install."
fi

echo "\"$WINE\" \"$WINEPREFIX/drive_c/oldsu/osu!flandremod.exe\" \"\$@\"" >> oldsu

mv oldsu $HOME/.bin/oldsu
chmod +x $HOME/.bin/oldsu

# Kill script
cat > oldsukill << "EOF"
#!/bin/sh
export WINEARCH=win32
EOF

echo "export WINEPREFIX=\"$WINEPREFIX\"" >> oldsukill
echo "\"$WINESERVER\" -k" >> oldsukill

mv oldsukill $HOME/.bin/oldsukill
chmod +x $HOME/.bin/oldsukill

# Desktop file
OLDSU_LOGO_URL="https://cdn.discordapp.com/attachments/762549406091575309/783088957776461824/oldsu.png"
wget "$OLDSU_LOGO_URL" -O "$HOME/.local/share/icons/oldsulogo.png"

cat > "oldsu!.desktop" << "EOF"
[Desktop Entry]

Encoding=UTF-8

Name=oldsu!

Comment=Travel back in time! Launch the 2008 o(ld)su! client.

Type=Application

Exec=oldsu %F

Icon=oldsulogo

StartupWMClass=osu!flandremod.exe

Categories=Games

EOF

mv "oldsu!.desktop" "$HOME/.local/share/applications"
chmod +x "$HOME/.local/share/applications/oldsu!.desktop"

# Cleanup
cd /tmp
rm -r "$TMP_DIR"

# Finished!
print_sect "Finished! Please report any issues with this script at https://github.com/marshallracer/osu-wine-install-script"

